---
title: "Prag Bat Round 2"
output: html_document

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)

library(tidyverse)
library(knitr)
library(ggthemes)
library(jsonlite)
library(readxl)
library(corrr)
library(corrplot)
library(ggcorrplot)
library(reshape2)
library(ggpubr)
#library(psych)
#library(readODS)
library(brms)
library(psy)
library(tidyboot)
library(lubridate)
library(BayesFactor)
library(lavaan)
library(lavaanPlot)
library(blavaan)


```

```{r}
files <- dir("~/Work/Cloud/PragBat/data_pragBat_3/")

files <- files[!(files %in% "Readme.md")]

files <- files[!(files %in% "Zoom_cm_ds_mOiwQPmhNRhg3z2Gkbp4KkeEaAgbCMsKgSXO4@h1k-gahL5FRePqGv_k0e14986e25507af5_.exe")]



raw_data <- data_frame()
for (f in files) {
  jf <- paste("~/Work/Cloud/PragBat/data_pragBat_3/",f,sep="")
  jd <- jsonlite::fromJSON(paste(readLines(jf), collapse=""))
  date <- str_sub(jf,-22,str_length(jf)-14)
  id <- as_data_frame(jd) %>% mutate(test_date = date,
                                              trial = as.character(trial))
  raw_data <- bind_rows(raw_data, id)
}

task_data <- raw_data%>%
  filter(!grepl("train",trial),
         !grepl("fill",trial))%>%
  filter(phase == "shape" | is.na(phase))%>%
  mutate(subid = ifelse(subid == "265011", "260934", subid))


log <- read_xlsx("../../../../Cloud/PragBat/vpl_pragBat3.xlsx", sheet = 1)%>%
  mutate(age = as.numeric(difftime(as.Date(as.character(test_day),format="%Y%m%d"), as.Date(as.character(birthday),format="%Y%m%d"), units = "days"))/365.25,
         age_num_month = lubridate::time_length(difftime(as.Date(as.character(test_day),format="%Y%m%d"), as.Date(as.character(birthday),format="%Y%m%d")), "month"),
          age_month = round(age_num_month)/12,
         id = ID,
         subid = as.character(`Data ID`))%>%
  select(id, subid, age, gender,age_month, status)

data <- log %>%
  left_join(task_data)%>%
  filter(status == "keep")%>%
  mutate(check_age = ifelse(subage == substr(age,1,1),T,F),
         subage = as.numeric(substr(age,1,1)),
          subage = ifelse(subage == 5, 4, subage),
         subage = factor(subage),
         trial = as.numeric(trial))%>%
    select(id, subage,age,gender, task,item, trial, correct)


write_csv(data, "../data/data_r3.csv")

data <- read_csv("../data/data_r3.csv")

```

```{r}
data%>%
  group_by(subage, gender)%>%
  summarise(n= length(unique(id)))

data%>%
  summarise(n= length(unique(id)))
```

```{r}
data%>%
  group_by(id)%>%
  summarise(n= n())
```


```{r}
data%>%
  group_by(id)%>%
  summarise(age = min(age))%>%
  ggplot(aes(x = age, y = 0))+
  geom_point(alpha = 0.25, size = 5)+
  xlim(3,5)+
  ylim(-0.1,0.1)+
  theme_minimal()+
  labs(x = "Age", y = "")+
  theme(axis.text.y = element_blank())
```

```{r}
p1 <- data%>%
  group_by(id,age, subage,task)%>%
  filter(task != "training")%>%
  summarise(mean = mean(correct))

p2 <- p1 %>%
  group_by(subage,task)%>%
  tidyboot_mean(column = mean)%>%
  mutate(chance = 1/2)

ggplot()+
  geom_hline(data = p2, aes(yintercept = chance), lty = 2)+
  geom_smooth(data = p1, aes(x = age, y = mean), method = "lm", col = "black", size = 1)+
  geom_point(data = p1, aes(x = age, y = mean), alpha = .5, width = .05, height = .01)+
  geom_pointrange(data = p2, aes(x = as.numeric(as.character(subage))+.5, y = mean, ymin = ci_lower, ymax = ci_upper, col = subage))+
  facet_wrap(~task)+
  labs(x = "Age Group", y = "Proportion Correct")+
  scale_color_ptol(name = "Age")+
  ylim(-0.05, 1.05)+
  xlim(3,5)+
  theme_few()+
  theme(legend.position = c(.85,.2))
```

```{r}
x <- ttestBF(p1%>%filter(task == "match_to_sample")%>%pull(mean), mu = 0.5)

extractBF(x)
```


```{r}
data%>%
  filter(task !="training")%>%
  mutate(test_half = ifelse( trial %% 2, "even", "odd"))%>%
  group_by(id, task, test_half)%>%
  summarise(mean = mean(correct))%>%
  pivot_wider(names_from = test_half, values_from = mean)%>%
  group_by(task)%>%
  summarise(cor = cor (even, odd))
```


```{r}
cor <- data%>%
  filter(task != "training")%>%
  droplevels()%>%
  group_by(id,task)%>%
  summarise(mean = mean(correct))%>%
  spread(task, mean)%>%
  ungroup()%>%
  select(-id)%>%
  corrr::correlate()%>%
  gather(task, cor, -term)%>%
  mutate(cor = replace(cor, duplicated(cor), NA))%>%
  mutate_if(is.numeric, round, digits = 2)%>%
  na.omit()
  

ggplot(cor, aes(x = term, y = task, fill = cor))+
  geom_tile(color = "white")+
  labs(x = "", y = "")+
  scale_fill_gradient2(low = "#CC6677", high = "#117733", mid = "white", 
   midpoint = 0, limit = c(-1,1), space = "Lab", 
   name="Correlation") +
   coord_fixed()+
  theme_few(base_size = 12)+
  geom_text(aes(label = cor), color = "black", size = 3) +
  theme(legend.justification = c(1, 0),
        legend.position = c(0.55, 0.75),
        legend.direction = "horizontal",
        axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1), 
        legend.background = element_blank())+
  guides(fill = guide_colorbar(barwidth = 7, barheight = 1,
                title.position = "top", title.hjust = 0.5))
```


```{r}
cp <- data%>%
  group_by(id,age, subage,task)%>%
  filter(task != "training")%>%
  summarise(mean_task1 = mean(correct))%>%
  left_join(p1 %>% rename(task2 = task, mean_task2 = mean),by = c("id","age","subage"))%>%
  filter(task != task2)%>%
  rowwise()%>%
  mutate(ex = paste(sort(c(task, task2)), collapse = " - "))%>%
  distinct(ex, .keep_all = T)
  

ggplot(cp, aes(x = mean_task1, y = mean_task2))+
  geom_count( alpha = .25)+
  geom_abline(intercept = 0 , slope = 1, lty = 2, alpha = .4)+
  facet_grid(task2~task)+
  theme_few()+
  geom_smooth(method = lm)+
  stat_cor(method = "pearson", size = 3, r.accuracy = 0.01, cor.coef.name = "r")+
  scale_x_continuous(breaks = c(0,1))+
  scale_y_continuous(breaks = c(0,1))

```
# Models 
```{r}
data_card <- data%>%
  filter(task == "card_sorting")%>%
  mutate(z_age = scale(age),
         z_trial = scale(trial))

m_card <- brm(correct ~ z_age + z_trial + (z_trial|id),
                    data = data_card, family = bernoulli(),
          control = list(adapt_delta = 0.8),
          sample_prior = F,
          chains = 4,
          cores = 4,
          iter = 2000)


data_me<- data%>%
  filter(task == "mutual_exclusivity")%>%
  mutate(z_age = scale(age),
         z_trial = scale(trial))

m_card <- brm(correct ~ z_age + z_trial + (z_trial|id),
                    data = data_card, family = bernoulli(),
          control = list(adapt_delta = 0.8),
          sample_prior = F,
          chains = 4,
          cores = 4,
          iter = 2000)

```


# SEM playground

```{r}
library(lavaan)
library(OpenMx)
library(tidySEM)
library(blavaan)
```

```{r}
semd <- p1%>%
  pivot_wider(names_from = "task", values_from = "mean")%>%
  ungroup()%>%
  filter(!is.na(ad_hoc_implicature),
         !is.na(card_sorting),
         !is.na(match_to_sample),
         !is.na(mutual_exclusivity),
         !is.na(simple_inf))%>%
  mutate(ad_hoc_implicature = scale(ad_hoc_implicature),
         card_sorting = scale(card_sorting),
         match_to_sample = scale(match_to_sample),
         mutual_exclusivity = scale(mutual_exclusivity),
         simple_inf = scale(simple_inf))

model <- 'prag  =~ ad_hoc_implicature + mutual_exclusivity + simple_inf
          card  =~ card_sorting
          match =~ match_to_sample'

model2 <- 'fac  =~ ad_hoc_implicature + mutual_exclusivity + simple_inf + card_sorting + match_to_sample'

model3 <- 'ad  =~ ad_hoc_implicature
           simp  =~ simple_inf
           mut  =~ mutual_exclusivity
           card  =~ card_sorting
           match =~ match_to_sample'
```



```{r}
ffit <- cfa(model, data = semd)

ffit2 <- cfa(model2, data = semd)

ffit3 <- cfa(model3, data = semd)

summary(ffit, fit.measures=TRUE, standardized = TRUE)

lavTestLRT(ffit,ffit2 )
```


```{r}
lay <- get_layout("card", "", "prag","","match",
                  "card_sorting", "ad_hoc_implicature", "mutual_exclusivity", "simple_inf", "match_to_sample", rows = 2)

graph_sem(model = ffit, layout = lay)
```


```{r}
fit <- bcfa(model, data = semd, bcontrol = list(cores = 3), target = "stan", n.chains = 3, burnin = 2000, sample = 2000)

fit2 <- bcfa(model2, data = semd, bcontrol = list(cores = 3), target = "stan", n.chains = 3, burnin = 2000, sample = 2000)

fit3 <- bcfa(model3, data = semd, bcontrol = list(cores = 3), target = "stan", n.chains = 3, burnin = 2000, sample = 2000)

blavCompare(fit, fit2)

blavCompare(fit, fit3)

blavInspect(fit, "lvs")
```


```{r}
summary(fit, fit.measures=TRUE, standardized = TRUE)
```


