---
title: "Data simulations"
author: "M. Bohn"
date: "27 8 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(tmvnsim)
library(corrr)
library(corrplot)
library(Hmisc)
library(ggthemes)

```


```{r}
sim <- function(seed,trials,sig) {
 
set.seed(seed)
  
low <- rep(0, 5)
high <- rep(1, 5)
sig <- matrix(sig, 5, 5)
diag(sig) <- 1
res <- tmvnsim(nsamp=100, k=5, lower=low, upper=high, imod=rep(F, 5)
		, means=rep(0, 5), sigma=sig)%>%
  as_tibble()


cuts = trials +1
breaks = seq(0,1,length.out = cuts+1)
labels = seq(0,1,length.out = trials+1)

x <- res$samp %>% 
  as_tibble()

mean_con <- correlate(x) %>%
  gather(key, value)%>%
  filter(key !="rowname")%>%
  na.omit()%>%
  summarise(mean_con = mean(as.numeric(value)))

x_2 <- res$samp %>% 
  as_tibble()%>%
  mutate(V1 = as.numeric(as.character(cut(V1, breaks = breaks, labels = labels))),
         V2 = as.numeric(as.character(cut(V2, breaks = breaks, labels = labels))),
         V3 = as.numeric(as.character(cut(V3, breaks = breaks, labels = labels))),
         V4 = as.numeric(as.character(cut(V4, breaks = breaks, labels = labels))),
         V5 = as.numeric(as.character(cut(V5, breaks = breaks, labels = labels))))

mean_bin <- correlate(x_2) %>%
  gather(key, value)%>%
  filter(key !="rowname")%>%
  na.omit()%>%
  summarise(mean_bin = mean(as.numeric(value)))

bind_cols(mean_con, mean_bin)

}
```


```{r}
n_sim = 1000

sim_6 <-
  tibble(seed = 1:n_sim) %>% 
  mutate(tidy = map(seed, sim, sig = .95, trials = 6))%>%
  unnest(tidy)%>%
  gather(type, corr, -seed)%>%
  mutate(trials = "6")

sim_5 <-
  tibble(seed = 1:n_sim) %>% 
  mutate(tidy = map(seed, sim, sig = .95, trials = 5))%>%
  unnest(tidy)%>%
  gather(type, corr, -seed)%>%
  mutate(trials = "5")

sim_4 <-
  tibble(seed = 1:n_sim) %>% 
  mutate(tidy = map(seed, sim, sig = .95, trials = 4))%>%
  unnest(tidy)%>%
  gather(type, corr, -seed)%>%
  mutate(trials = "4")

sim_3 <-
  tibble(seed = 1:n_sim) %>% 
  mutate(tidy = map(seed, sim, sig = .95, trials = 3))%>%
  unnest(tidy)%>%
  gather(type, corr, -seed)%>%
  mutate(trials = "3")

sim_2 <-
  tibble(seed = 1:n_sim) %>% 
  mutate(tidy = map(seed, sim, sig = .95, trials = 2))%>%
  unnest(tidy)%>%
  gather(type, corr, -seed)%>%
  mutate(trials = "2")

sim_1 <-
  tibble(seed = 1:n_sim) %>% 
  mutate(tidy = map(seed, sim, sig = .95, trials = 1))%>%
  unnest(tidy)%>%
  gather(type, corr, -seed)%>%
  mutate(trials = "1")


sim_plot = bind_rows(
  sim_6,
  sim_5,
  sim_4,
  sim_3,
  sim_2,
  sim_1
)

ggplot(sim_plot, aes(x = corr, fill = type))+
  geom_density(alpha = .5)+
  xlim(0,1)+
  facet_grid(trials~.)+
  theme_few()+
  scale_fill_ptol()
  
```


```{r}

n_sim = 1000

sim_4_r05 <-
  tibble(seed = 1:n_sim) %>% 
  mutate(tidy = map(seed, sim, sig = .95, trials = 5))%>%
  unnest(tidy)%>%
  gather(type, corr, -seed)%>%
  mutate(trials = "2", 
         cor = ".5")

sim_4_r03 <-
  tibble(seed = 1:n_sim) %>% 
  mutate(tidy = map(seed, sim, sig = .90, trials = 5))%>%
  unnest(tidy)%>%
  gather(type, corr, -seed)%>%
  mutate(trials = "1", 
         cor = ".3")


sim_plot_cor = bind_rows(
  sim_4_r05,
  sim_4_r03
)

ggplot(sim_plot_cor, aes(x = corr, fill = type))+
  geom_density(alpha = .5)+
  xlim(0,1)+
  facet_grid(cor~.)+
  theme_few()+
  scale_fill_ptol()
```


```{r}
library(bindata)

# Parameters of joint distribution
size <- 1
p1 <- 0.7
p2 <- 0.6
rho<- 0.3

# Create one pair of correlated binomial values
trials <- rmvbin(size, c(p1,p2), bincorr=(1-rho)*diag(2)+rho)
colSums(trials)

# A function to create n correlated pairs
rmvBinomial <- function(id, n, size, p1, p2, rho) {
    X <- replicate(n, {
             colSums(rmvbin(size, c(p1,p2), bincorr=(1-rho)*diag(2)+rho))
         })
    t(X)%>%
  as_tibble()%>%
      mutate(trial = 1:n, 
             id = id)%>%
      gather(task, score, -trial, -id)
}
# Try it out, creating 1000 pairs

sim2 <- function (seed, n_trials) {

n_sub = 100

set.seed(seed)

tibble(id = 1:n_sub) %>% 
  mutate(tidy = map(id, rmvBinomial, n =n_trials, size=size, p1=p1, p2=p2, rho=rho))%>%
  unnest(tidy)%>%
  group_by(id, task)%>%
  summarise(mean= mean(score))%>%
  spread(task, mean)%>%
  ungroup()%>%
  summarise(cor = cor(V1,V2))
  
}

n_sim = 1000

cor_sim_5 <- tibble(seed = 1:n_sim) %>% 
  mutate(tidy = map(seed, sim2, n_trials = 5))%>%
  unnest(tidy)%>%
  mutate(trials = "5")


cor_sim_4 <- tibble(seed = 1:n_sim) %>% 
  mutate(tidy = map(seed, sim2, n_trials = 4))%>%
  unnest(tidy)%>%
  mutate(trials = "4")

cor_sim_3 <- tibble(seed = 1:n_sim) %>% 
  mutate(tidy = map(seed, sim2, n_trials = 3))%>%
  unnest(tidy)%>%
  mutate(trials = "3")

cor_sim_2 <- tibble(seed = 1:n_sim) %>% 
  mutate(tidy = map(seed, sim2, n_trials = 2))%>%
  unnest(tidy)%>%
  mutate(trials = "2")


sim_plot_cor = bind_rows(
  cor_sim_5,
  cor_sim_4,
  cor_sim_3,
  cor_sim_2
)

ggplot(sim_plot_cor, aes(x = cor, fill = trials))+
  geom_density(alpha = .5)+
  geom_vline(xintercept = .3)+
  xlim(0,1)+
  theme_few()+
  scale_fill_ptol()
```


