---
title: "Data Processing"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(knitr)
library(langcog)
library(ggthemes)
library(jsonlite)
library(readxl)
library(corrr)
library(corrplot)
library(ggcorrplot)
library(reshape2)
library(psych)
library(readODS)
library(brms)

```


```{r}
# importing data
### die flogenden Zeilen kannst du überspringen. Weiter gehts in Zeile 68
# files <- dir("~/Work/PragBat/raw_data/")
# 
# raw_data <- data_frame()
# for (f in files) {
#   jf <- paste("~/Work/PragBat/raw_data/",f,sep="")
#   jd <- jsonlite::fromJSON(paste(readLines(jf), collapse=""))
#   date <- str_sub(jf,33,str_length(jf)-11)
#   id <- as_data_frame(jd$data$data) %>% mutate(test_date = date, 
#                                                trial = as.character(trial))
#   raw_data <- bind_rows(raw_data, id)
# }
# 
# unique(raw_data$subid)
# 
# 
# task_data <- raw_data %>%
#   filter(trial != "training", 
#          trial != "filler1", 
#          trial != "filler2",
#          trial != "train",
#          trial != "train2")%>%
#   filter(phase == "shape" | is.na(phase))%>%
#   mutate(subid = recode(subid, `13.2` = "Vp13.2",
#                         `13.2` = "Vp13.2",
#                         `14.2` = "Vp14.2",
#                         `16.2` = "Vp16.2",
#                         `19.1` = "Vp19.1",
#                         `12.1` = "Vp12.1",
#                         `29.2` = "Vp29.2",
#                         `26.1` = "Vp26.2",
#                         `37.1` = "Vp37.1",
#                         `38.1` = "Vp38.1"
#                         ))%>%
#   select(subid, subage, test_date, task, trial, correct)%>%
#   separate(subid, into = c("id","test_day"), sep="\\.")%>%
#   mutate(test_day = ifelse(id == "Vp12" & test_date =="2019-11-26", 2, test_day))


#write_csv(task_data, "../data/data.csv")

#task_data <- read_csv("../data/data.csv")

# damit du das daten file mit dem log file (deine Liste) mergen kannst (brauchen wir für das numerische alter) legst du deine liste in den gleichen ordner in dem auch ader repository ordner liegt. Dann sollte es klappen.

# log <- read_ods("../../VP Liste.ods", sheet = 2)%>%
#   mutate(age = as.numeric(difftime(test_day_1, `birthday `, units = "days"))/365.25,
#          id = paste("Vp",`ID `, sep = ""))%>%
#   select(id, age, status)
#   
# 
# data <- task_data %>%
#   left_join(log)%>%
#   mutate(check_age = ifelse(subage == substr(age,1,1),T,F))


data <- read_csv("../data/data.csv")%>%
  mutate(subage = factor(subage),
         trial = ifelse(test_day == "2", trial + 4, trial),
         z_age = age - mean(age))%>%
  select(-X)


```

```{r}
data%>%
  group_by(subage)%>%
  summarise(n= length(unique(id)))

```

```{r}
data %>%
  group_by(subage,id)%>%
  summarise(testdays = length(unique(test_day)))%>%
  filter(testdays == 2)%>%
  summarise(complete_retest_data = length(id))
```



```{r}
data %>%
  group_by(id,test_day)%>%
  summarise(n())%>%
  arrange(id,test_day)
 
```


```{r}
data%>%
  group_by(test_day,task)%>%
  summarise(n= length(unique(id)))
```

```{r}
p1 <- data%>%
  group_by(id,subage,task)%>%
  filter(task != "training")%>%
  summarise(mean = mean(correct))


p2 <- p1 %>%
  group_by(subage,task)%>%
  multi_boot_standard(col = "mean")

ggplot()+
  geom_hline(yintercept = .5, lty = 2)+
  geom_line(data = p2,aes(x = subage, y = mean, group = task), alpha = .5)+
  geom_jitter(data = p1, aes(x = subage, y = mean, col = subage), alpha = .5, width = .2, height = .01)+
  geom_pointrange(data = p2, aes(x = subage, y = mean, ymin = ci_lower, ymax = ci_upper, col = subage))+
  facet_wrap(~task)+
  labs(x = "Age Group", y = "Proportion Correct")+
  scale_color_ptol(name = "Age")+
  theme_few()+
  theme(legend.position = c(.85,.2))
```


```{r}
p12 <- data%>%
  group_by(id,age,task)%>%
  filter(task != "training")%>%
  summarise(mean = mean(correct))


ggplot(data = p12, aes(x = age, y = mean))+
  geom_hline(yintercept = .5, lty = 2)+
  geom_jitter(alpha = .5, width = .2, height = .01)+
  geom_smooth(method = "glm")+
  facet_grid(~task)+
  labs(x = "Age", y = "Proportion Correct")+
  scale_color_ptol(name = "Age")+
  theme_few()+
  theme(legend.position = c(.85,.2))+
  coord_fixed(ratio = 2)
```
# Models

## Card Sorting

```{r}
# card sorting

card_sorting_data <- data %>%
  filter(task == "card_sorting")


card_sorting_model_data <- card_sorting_data %>%
  mutate(trial = trial - mean(trial))

# card_sorting_model1 <- brm(correct ~ z_age + trial + (trial|id),
#                     data = card_sorting_model_data, family = bernoulli(),
#           control = list(adapt_delta = 0.99),
#           sample_prior = F,
#           chains = 4, 
#           cores = 4,
#           save_all_pars = TRUE,
#           iter = 10000)%>%
#   add_criterion("waic")%>%
#   saveRDS(., "../saves/card_sorting_model1.rds")
# 
# card_sorting_model2 <- brm(correct ~ trial + (trial|id),
#                     data = card_sorting_model_data, family = bernoulli(),
#           control = list(adapt_delta = 0.99),
#           sample_prior = F,
#           chains = 4, 
#           cores = 4,
#           save_all_pars = TRUE,
#           iter = 10000)%>%
#   add_criterion("waic")%>%
#   saveRDS(., "../saves/card_sorting_model2.rds")

card_sorting_model1 <-readRDS("../saves/card_sorting_model1.rds")

card_sorting_model2 <-readRDS("../saves/card_sorting_model2.rds")


cs_ts <- loo_compare(card_sorting_model1, card_sorting_model2, criterion = "waic")%>%
  as.data.frame() %>%
  tibble::rownames_to_column("Model")%>%
  mutate(
    Model = recode(Model, card_sorting_model1 = "correct ~ age + trial + RE", 
                   card_sorting_model2 = "correct ~ trial + RE"),
    weight = exp(elpd_waic) / sum(exp(elpd_waic)),
    weight = round(weight, 3),
    WAIC = round(waic, 2),
    SE = round(se_waic,2))%>%
  select(Model, WAIC, SE, weight)

cs_ts

summary(card_sorting_model1)

```

## Inforamtiveness

```{r}

inf_data <- data %>%
  filter(task == "informativeness")


inf_model_data <- inf_data %>%
  mutate(trial = trial - mean(trial))

inf_model1 <- brm(correct ~ z_age + trial + (trial|id),
                    data = inf_model_data, family = bernoulli(),
          control = list(adapt_delta = 0.99),
          sample_prior = F,
          chains = 4,
          cores = 4,
          save_all_pars = TRUE,
          iter = 10000)%>%
  add_criterion("waic")%>%
  saveRDS(., "../saves/inf_model1.rds")

inf_model2 <- brm(correct ~ trial + (trial|id),
                    data = inf_model_data, family = bernoulli(),
          control = list(adapt_delta = 0.99),
          sample_prior = F,
          chains = 4,
          cores = 4,
          save_all_pars = TRUE,
          iter = 10000)%>%
  add_criterion("waic")%>%
  saveRDS(., "../saves/inf_model2.rds")

inf_model1 <-readRDS("../saves/inf_model1.rds")

inf_model2 <-readRDS("../saves/inf_model2.rds")


inf_ts <- loo_compare(inf_model1, inf_model2, criterion = "waic")%>%
  as.data.frame() %>%
  tibble::rownames_to_column("Model")%>%
  mutate(
    Model = recode(Model, inf_model1 = "correct ~ age + trial + RE", 
                   inf_model2 = "correct ~ trial + RE"),
    weight = exp(elpd_waic) / sum(exp(elpd_waic)),
    weight = round(weight, 3),
    WAIC = round(waic, 2),
    SE = round(se_waic,2))%>%
  select(Model, WAIC, SE, weight)

inf_ts

summary(inf_data_model1)

```

## Mutual Exclusivity

```{r}

me_data <- data %>%
  filter(task == "mutual_exclusivity")


me_model_data <- me_data %>%
  mutate(trial = trial - mean(trial))

me_model1 <- brm(correct ~ z_age + trial + (trial|id),
                    data = me_model_data, family = bernoulli(),
          control = list(adapt_delta = 0.99),
          sample_prior = F,
          chains = 4,
          cores = 4,
          save_all_pars = TRUE,
          iter = 10000)%>%
  add_criterion("waic")%>%
  saveRDS(., "../saves/me_model1.rds")

me_model2 <- brm(correct ~ trial + (trial|id),
                    data = me_model_data, family = bernoulli(),
          control = list(adapt_delta = 0.99),
          sample_prior = F,
          chains = 4,
          cores = 4,
          save_all_pars = TRUE,
          iter = 10000)%>%
  add_criterion("waic")%>%
  saveRDS(., "../saves/me_model2.rds")

me_model1 <-readRDS("../saves/me_model1.rds")

me_model2 <-readRDS("../saves/me_model2.rds")


me_ts <- loo_compare(me_model1, me_model2, criterion = "waic")%>%
  as.data.frame() %>%
  tibble::rownames_to_column("Model")%>%
  mutate(
    Model = recode(Model, me_model1 = "correct ~ age + trial + RE", 
                   me_model2 = "correct ~ trial + RE"),
    weight = exp(elpd_waic) / sum(exp(elpd_waic)),
    weight = round(weight, 3),
    WAIC = round(waic, 2),
    SE = round(se_waic,2))%>%
  select(Model, WAIC, SE, weight)

me_ts

summary(me_model1)

```
## Novelty

```{r}

nov_data <- data %>%
  filter(task == "novelty")


nov_model_data <- nov_data %>%
  mutate(trial = trial - mean(trial))

nov_model1 <- brm(correct ~ z_age + trial + (trial|id),
                    data = nov_model_data, family = bernoulli(),
          control = list(adapt_delta = 0.99),
          sample_prior = F,
          chains = 4,
          cores = 4,
          save_all_pars = TRUE,
          iter = 10000)%>%
  add_criterion("waic")%>%
  saveRDS(., "../saves/nov_model1.rds")

nov_model2 <- brm(correct ~ trial + (trial|id),
                    data = nov_model_data, family = bernoulli(),
          control = list(adapt_delta = 0.99),
          sample_prior = F,
          chains = 4,
          cores = 4,
          save_all_pars = TRUE,
          iter = 10000)%>%
  add_criterion("waic")%>%
  saveRDS(., "../saves/nov_model2.rds")

nov_model1 <-readRDS("../saves/nov_model1.rds")

nov_model2 <-readRDS("../saves/nov_model2.rds")


nov_ts <- loo_compare(nov_model1, nov_model2, criterion = "waic")%>%
  as.data.frame() %>%
  tibble::rownames_to_column("Model")%>%
  mutate(
    Model = recode(Model, nov_model1 = "correct ~ age + trial + RE", 
                   nov_model2 = "correct ~ trial + RE"),
    weight = exp(elpd_waic) / sum(exp(elpd_waic)),
    weight = round(weight, 3),
    WAIC = round(waic, 2),
    SE = round(se_waic,2))%>%
  select(Model, WAIC, SE, weight)

nov_ts

summary(nov_model1)

```
# Visualizing individual tasks

```{r}
# Files to plot data means
p_data <- data %>%
  filter(task != "training")%>%
  mutate(subage = as.numeric(as.character(subage)))%>%
  group_by(task, age,subage,id) %>%
  summarise(correct = mean(correct)) 

p_data2 <- p_data %>%
  group_by(task, subage) %>%
  multi_boot_standard(col = "correct")


# Files to plot individual samples from each task
samples_to_draw <- sample(1:20000, 500)

## card sorting
samples_cs <- posterior_samples(card_sorting_model1, "^b")%>%
  mutate(sample = 1:length(b_age))%>%
  filter(sample %in% samples_to_draw)%>%
  expand_grid(data$z_age)%>%
  mutate(y = plogis(b_Intercept + b_age * `data$z_age`),
         age = `data$z_age` + mean(data$age),
         task = "card_sorting")

## informativeness
samples_inf <- posterior_samples(inf_model1, "^b")%>%
  mutate(sample = 1:length(b_age))%>%
  filter(sample %in% samples_to_draw)%>%
  expand_grid(data$z_age)%>%
  mutate(y = plogis(b_Intercept + b_age * `data$z_age`),
         age = `data$z_age` + mean(data$age),
         task = "informativeness")

## mutual exclusivity
samples_me <- posterior_samples(me_model1, "^b")%>%
  mutate(sample = 1:length(b_z_age))%>%
  filter(sample %in% samples_to_draw)%>%
  expand_grid(data$z_age)%>%
  mutate(y = plogis(b_Intercept + b_z_age * `data$z_age`),
         age = `data$z_age` + mean(data$age),
         task = "mutual_exclusivity")
## novelty

samples_nov <- posterior_samples(nov_model1, "^b")%>%
  mutate(sample = 1:length(b_z_age))%>%
  filter(sample %in% samples_to_draw)%>%
  expand_grid(data$z_age)%>%
  mutate(y = plogis(b_Intercept + b_z_age * `data$z_age`),
         age = `data$z_age` + mean(data$age),
         task = "novelty")

## combine files
samples <- bind_rows(
  samples_cs,
  samples_inf,
  samples_me,
  samples_nov
)


# File to plot means of distributions for each task

## card sorting
map_cs <- tibble(
  age = data$z_age,
  int = fixef(card_sorting_model1)[1,1],
  slope = fixef(card_sorting_model1)[2,1]
)%>%
  mutate(y = plogis(int + slope * age),
         age = age + mean(data$age),
         task = "card_sorting")

## informativeness
map_inf <- tibble(
  age = data$z_age,
  int = fixef(inf_model1)[1,1],
  slope = fixef(inf_model1)[2,1]
)%>%
  mutate(y = plogis(int + slope * age),
         age = age + mean(data$age),
         task = "informativeness")

## mutual exclusivity
map_me <- tibble(
  age = data$z_age,
  int = fixef(me_model1)[1,1],
  slope = fixef(me_model1)[2,1]
)%>%
  mutate(y = plogis(int + slope * age),
         age = age + mean(data$age),
         task = "mutual_exclusivity")

## novelty
map_nov <- tibble(
  age = data$z_age,
  int = fixef(nov_model1)[1,1],
  slope = fixef(nov_model1)[2,1]
)%>%
  mutate(y = plogis(int + slope * age),
         age = age + mean(data$age),
         task = "novelty")



maps <- bind_rows(
  map_cs,
  map_inf,
  map_me,
  map_nov
)


ggplot() +
  geom_hline(yintercept = .5, lty=2, size = 1)+
  geom_line(data = samples, aes(x = age, y = y, group = sample), size = .025, col = "grey")+
  geom_line(data = maps, aes(x = age, y = y), size = 1)+
  geom_jitter(data = p_data,aes(x = age, y= correct), width = .00, height = .01, alpha = .2)+
  geom_pointrange(data = p_data2, aes(x = subage+.5, y = mean, ymin = ci_lower, ymax = ci_upper),size = .5, position = position_dodge(width = .2), pch = 5, col = "#6866cc")+
  labs(x="Age",y="Proportion correct")+
  facet_wrap(~task, nrow = 1)+
  theme_few() +
  ylim(-0.05,1.05)+
  xlim(3,5)+
  guides(alpha = F, col = F)+
  coord_fixed(ratio = 2)+
  ggsave("../graphs/task_results.png", width = 10, height = 2.5, scale = 1.2)
```

# Visualizing predictor for age

```{r}

library(ggridges)

x <- bind_rows(
  posterior_samples(card_sorting_model1, "^b")%>%
  select(b_age)%>%
  mutate(task = "1 card_sorting",
         ci = ifelse(b_age < fixef(card_sorting_model1)[2,3] | b_age > fixef(card_sorting_model1)[2,4], 1,2)),
  posterior_samples(inf_model1, "^b")%>%
  select(b_age)%>%
  mutate(task = "4 informativeness",
         ci = ifelse(b_age < fixef(inf_model1)[2,3] | b_age > fixef(inf_model1)[2,4], 1,2)),
  posterior_samples(nov_model1, "^b")%>%
  select(b_z_age)%>%
  rename(b_age = b_z_age)%>%
  mutate(task = "2 novelty",
         ci = ifelse(b_age < fixef(nov_model1)[2,3] | b_age > fixef(nov_model1)[2,4], 1,2)),
  posterior_samples(me_model1, "^b")%>%
  select(b_z_age)%>%
  rename(b_age = b_z_age)%>%
  mutate(task = "3 mutual_exclusivity",
         ci = ifelse(b_age < fixef(me_model1)[2,3] | b_age > fixef(me_model1)[2,4], 1,2))
)
  

ggplot(x, aes(x = b_age, y = task, fill = factor(stat(quantile))))+
  geom_vline(xintercept = 0, col = "grey", lty = 2)+
  stat_density_ridges(
    geom = "density_ridges_gradient",
    calc_ecdf = TRUE,
    quantiles = c(0.025, 0.975)
  ) +
  scale_fill_manual(values = c("white", "lightblue", "white"))+ 
  guides(fill = F)+
  xlim(-10,20)+
  theme_few()

```


```{r}
p3 <- data%>%
  filter(task != "training")%>%
  group_by(id,task, test_day)%>%
  summarise(mean = mean(correct))%>%
  spread(test_day, mean)%>%
  rename("Day1" = `1`,
         "Day2" = `2`)%>%
  na.omit()

ggplot(p3, aes(x = Day1, y = Day2))+
  geom_jitter(width = .05, height = .05, alpha = .5)+
  geom_abline(intercept = 0, slope = 1, lty = 2, alpha = 0.7, size = 0.5)+
  geom_smooth(method = "lm", col = "#af6300", se = T)+
  facet_grid(~task)+
  coord_fixed()+
  xlim(-.1,1.1)+
  ylim(-.1,1.1)+
  theme_few()

```



```{r}
reli <- data%>%
  filter(task != "training")%>%
  droplevels()%>%
  group_by(id,task, test_day)%>%
  summarise(mean = mean(correct))%>%
  spread(test_day, mean)%>%
  na.omit()%>%
  rename("Day1" = `1`,
         "Day2" = `2`)%>%
  group_by(task)%>%
  summarize(reli = cor.test(Day1,Day2)$estimate,
            lci = cor.test(Day1,Day2)$conf.int[1],
            uci = cor.test(Day1,Day2)$conf.int[2],
            p = cor.test(Day1,Day2)$p.value)%>%
  mutate_if(is.numeric, round, digits = 2)


reli
```

```{r}
reli_age <- data%>%
  filter(task != "training")%>%
  droplevels()%>%
  group_by(subage, id,task, test_day)%>%
  summarise(mean = mean(correct))%>%
  spread(test_day, mean)%>%
  na.omit()%>%
  rename("Day1" = `1`,
         "Day2" = `2`)%>%
  group_by(subage,task)%>%
  summarize(reli = cor.test(Day1,Day2)$estimate,
            lci = cor.test(Day1,Day2)$conf.int[1],
            uci = cor.test(Day1,Day2)$conf.int[2],
            p = cor.test(Day1,Day2)$p.value)%>%
  mutate_if(is.numeric, round, digits = 2)


reli_age
```

```{r}
cor <- data%>%
  filter(task != "training")%>%
  droplevels()%>%
  group_by(id,task)%>%
  summarise(mean = mean(correct))%>%
  spread(task, mean)%>%
  ungroup()%>%
  select(-id)%>%
  corrr::correlate(diagonal = reli$reli)%>%
  gather(task, cor, -rowname)%>%
  mutate(cor = replace(cor, duplicated(cor), NA))%>%
  mutate_if(is.numeric, round, digits = 2)%>%
  na.omit()
  

ggplot(cor, aes(x = rowname, y = task, fill = cor))+
  geom_tile(color = "white")+
  labs(x = "", y = "")+
  scale_fill_gradient2(low = "#CC6677", high = "#117733", mid = "white", 
   midpoint = 0, limit = c(-1,1), space = "Lab", 
   name="Correlation") +
   coord_fixed()+
  theme_few(base_size = 12)+
  geom_text(aes(label = cor), color = "black", size = 3) +
  theme(legend.justification = c(1, 0),
        legend.position = c(0.55, 0.7),
        legend.direction = "horizontal",
        axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))+
  guides(fill = guide_colorbar(barwidth = 7, barheight = 1,
                title.position = "top", title.hjust = 0.5))
```

```{r}
library(psy)

fa_data <- p1 %>%
  spread(task, mean)%>%
  ungroup()%>%
  select(-id, -subage)%>%
  na.omit()
  

pca <- principal(fa_data,nfactors=2, rotate="varimax")

fit <- factanal(fa_data, 2, rotation="varimax")

scree.plot(fit$correlation)

fit$loadings

pca$loadings

plot(pca)

```


