---
title: "Prag Bat Round 2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)

library(tidyverse)
library(knitr)
library(langcog)
library(ggthemes)
library(jsonlite)
library(readxl)
library(corrr)
library(corrplot)
library(ggcorrplot)
library(reshape2)
library(psych)
library(readODS)
library(brms)
library(psy)

```

```{r}
## die flogenden Zeilen kannst du überspringen. Weiter gehts in Zeile 68
files <- dir("~/Work/PragBat/raw_data2/")

raw_data <- data_frame()
for (f in files) {
  jf <- paste("~/Work/PragBat/raw_data2/",f,sep="")
  jd <- jsonlite::fromJSON(paste(readLines(jf), collapse=""))
  date <- str_sub(jf,34,str_length(jf)-11)
  id <- as_data_frame(jd$data$data) %>% mutate(test_date = date,
                                               trial = as.character(trial))
  raw_data <- bind_rows(raw_data, id)
}

task_data <- raw_data%>%
  filter(trial != "training",
         trial != "filler1",
         trial != "filler2",
         trial != "train",
         trial != "train1",
         trial != "train2",
         task != "training")%>%
  filter(phase == "shape" | is.na(phase))%>%
  separate(subid, into = c("id","test_day"), sep="_")

log <- read_xlsx("../../pragBat2_vp_list.xlsx", sheet = 1)%>%
  mutate(age = as.numeric(difftime(test_day_1, birthday, units = "days"))/365.25,
         id = paste("VP",ID, sep = ""))%>%
  select(id, age, status)

data <- task_data %>%
  left_join(log)%>%
  filter(status == "keep")%>%
  mutate(check_age = ifelse(subage == substr(age,1,1),T,F),
         subage = factor(as.numeric(substr(age,1,1))),
         trial = as.numeric(trial))%>%
  mutate(trial = ifelse(test_day == "2", 
                        ifelse(task == "card_sorting", trial + 6, trial +5),
                        trial),
         z_age = age - mean(age),
         z_trial = trial - mean(trial))%>%
    select(id, test_day, subage,age, task, trial, agent, correct, z_age, z_trial)

write_csv(data, "../data/data_tom.csv")

data <- read_csv("../data/data_tom.csv")

  
```

```{r}
data%>%
  group_by(subage)%>%
  summarise(n= length(unique(id)))
```


```{r}
unique(data$id)
```


```{r}
data %>%
  group_by(subage,id)%>%
  summarise(testdays = length(unique(test_day)))%>%
  filter(testdays == 2)%>%
  summarise(complete_retest_data = length(id))
```

```{r}
raw_data%>%
  filter(task == "simple_inf")%>%
  separate(subid, into = c("id","test_day"), sep="_")%>%
  filter(trial == "filler1" | trial == "filler2")%>%
  group_by(id)%>%
  summarise(mean = mean(correct))
```


```{r}
p1 <- data%>%
  group_by(id,age, subage,task)%>%
  filter(task != "training")%>%
  summarise(mean = mean(correct))


p2 <- p1 %>%
  group_by(subage,task)%>%
  multi_boot_standard(col = "mean")%>%
  mutate(chance = ifelse(task == "discourse_continuity", 1/3, 1/2))

ggplot()+
  geom_hline(data = p2, aes(yintercept = chance), lty = 2)+
  geom_smooth(data = p1, aes(x = age, y = mean), method = "lm", col = "black", size = 1)+
  geom_jitter(data = p1, aes(x = age, y = mean), alpha = .5, width = .05, height = .01)+
  geom_pointrange(data = p2, aes(x = as.numeric(as.character(subage))+.5, y = mean, ymin = ci_lower, ymax = ci_upper, col = subage))+
  facet_wrap(~task)+
  labs(x = "Age Group", y = "Proportion Correct")+
  scale_color_ptol(name = "Age")+
  ylim(-0.05, 1.05)+
  theme_few()+
  theme(legend.position = c(.85,.2))
```





```{r}
p3 <- data%>%
  filter(task != "training")%>%
  group_by(id,task, test_day)%>%
  summarise(mean = mean(correct))%>%
  spread(test_day, mean)%>%
  rename("Day1" = `1`,
         "Day2" = `2`)%>%
  na.omit()

ggplot(p3, aes(x = Day1, y = Day2))+
  geom_jitter(width = .05, height = .05, alpha = .5)+
  geom_abline(intercept = 0, slope = 1, lty = 2, alpha = 0.7, size = 0.5)+
  geom_smooth(method = "lm", col = "#af6300", se = T)+
  facet_grid(~task)+
  coord_fixed()+
  xlim(-.1,1.1)+
  ylim(-.1,1.1)+
  theme_few()

```

```{r}
reli <- data%>%
  filter(task != "training")%>%
  droplevels()%>%
  group_by(id,task, test_day)%>%
  summarise(mean = mean(correct))%>%
  spread(test_day, mean)%>%
  na.omit()%>%
  rename("Day1" = `1`,
         "Day2" = `2`)%>%
  group_by(task)%>%
  summarize(reli = cor.test(Day1,Day2)$estimate,
            lci = cor.test(Day1,Day2)$conf.int[1],
            uci = cor.test(Day1,Day2)$conf.int[2],
            p = cor.test(Day1,Day2)$p.value)%>%
  mutate_if(is.numeric, round, digits = 2)
```



```{r}
cor <- data%>%
  filter(task != "training")%>%
  droplevels()%>%
  group_by(id,task)%>%
  summarise(mean = mean(correct))%>%
  spread(task, mean)%>%
  ungroup()%>%
  select(-id)%>%
  corrr::correlate(diagonal = reli$reli)%>%
  gather(task, cor, -rowname)%>%
  mutate(cor = replace(cor, duplicated(cor), NA))%>%
  mutate_if(is.numeric, round, digits = 2)%>%
  na.omit()
  

ggplot(cor, aes(x = rowname, y = task, fill = cor))+
  geom_tile(color = "white")+
  labs(x = "", y = "")+
  scale_fill_gradient2(low = "#CC6677", high = "#117733", mid = "white", 
   midpoint = 0, limit = c(-1,1), space = "Lab", 
   name="Correlation") +
   coord_fixed()+
  theme_few(base_size = 12)+
  geom_text(aes(label = cor), color = "black", size = 3) +
  theme(legend.justification = c(1, 0),
        legend.position = c(0.55, 0.7),
        legend.direction = "horizontal",
        axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))+
  guides(fill = guide_colorbar(barwidth = 7, barheight = 1,
                title.position = "top", title.hjust = 0.5))
```