---
title: "Prag Bat reliability"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)

library(tidyverse)
library(brms)
library(tidybayes)
library(ggpubr)
```

# Loading data
```{r}

raw_data <- bind_rows(
read_csv("../data/data_r1.csv")%>%mutate(id = paste(id,"r1",sep = "_"),study = "s1") ,
read_csv("../data/data_r2.csv")%>%mutate(id = paste(id,"r2",sep = "_"), study = "s2")
)%>%
  filter(task !="training")


complete_ids <- raw_data %>%
  group_by(subage,id)%>%
  summarise(testdays = length(unique(test_day)))%>%
  filter(testdays == 2)%>%
  pull(id)

data <- raw_data%>%
  filter(task != "training", 
         id %in% complete_ids)%>%
  mutate(test_day = ifelse(test_day == 1, "day1", "day2"),
         z_trial = scale(trial))

```
# Descriptives

```{r}
data %>%
  group_by(task)%>%
  summarise(n = length(unique(id)))
```

# Simple correaltions

```{r}
data%>%
  droplevels()%>%
  group_by(id,task, test_day)%>%
  summarise(mean = mean(correct))%>%
  spread(test_day, mean)%>%
  group_by(task)%>%
  summarize(reli = cor.test(day1,day2)$estimate,
            lci = cor.test(day1,day2)$conf.int[1],
            uci = cor.test(day1,day2)$conf.int[2],
            p = cor.test(day1,day2)$p.value)%>%
  mutate_if(is.numeric, round, digits = 2)

```
## Visualize simple correlations
```{r}
data%>%
  droplevels()%>%
  group_by(id,task, test_day)%>%
  summarise(mean = mean(correct))%>%
  spread(test_day, mean)%>%
  ggplot( aes(x = day1, y = day2))+
  geom_abline(intercept = 0, slope = 1, lty = 2, alpha = 1, size = .5)+
  geom_count(alpha = .5)+
  facet_wrap( ~ task)+
  stat_cor(method = "pearson",  aes(x = day1, y = day2), size = 2)+
  theme_minimal()+
  theme(aspect.ratio = 1)
```

# Model by task sensu Rouder and Haaf

## Task: Mutual exclusivity
```{r}
me_data <- data %>%
  filter(study == "s2", 
         task == "mutual_exclusivity")
```

```{r}
bme <-  brm(correct ~  z_age + test_day + (0+test_day|id),
                    data = me_data, 
            family = bernoulli(),
          #control = list(adapt_delta = 0.99),
          sample_prior = F,
          chains = 4,
          cores = 4,
          #save_all_pars = TRUE,
          iter = 2000)

rme <- ranef(bme)

rel_me <- as_tibble(rme$id[,,"test_dayday1"], rownames = "id")%>%
  left_join(as_tibble(rme$id[,,"test_dayday2"], rownames = "id")%>%
              rename(Estimate_d2 = Estimate,
                     Q2.5_d2 = Q2.5, 
                     Q97.5_2 = Q97.5, 
                     Est.Error_2 = Est.Error))


ggplot(rel_me, aes(x = Estimate, y = Estimate_d2))+
  geom_abline(intercept = 0, slope = 1, lty = 2, alpha = 0.7, size = 0.5)+
    geom_point(size = 5, pch = 4)+
  geom_errorbar(aes(ymin = Q2.5_d2, ymax = Q97.5_2),width = 0, alpha = .4)+
  geom_errorbarh(aes(xmin = Q2.5, xmax = Q97.5), height = 0, alpha = .4)+
  labs(x = "Day 1", y = "Day 2")+
  #facet_grid(~chain)+
  stat_cor(method = "pearson", aes(x = Estimate, y = Estimate_d2), inherit.aes = F, size = 3)+
  theme_minimal()
```

```{r}
me_age <- as_tibble(rme$id[,,"test_dayday1"], rownames = "id")%>%
  left_join(me_data)

cor(me_age$age, me_age$Estimate)

me_data%>%
  group_by(id)%>%
  summarise(age = mean(age),
            perf = mean(correct))%>%
  ungroup()%>%
  summarise(cor = cor(age ,perf))
  
```


## Task: Informativeness
```{r}
inf_data <- data %>%
  filter(#study == "s2", 
         task == "informativeness")
```

```{r}
binf <-  brm(correct ~  z_age + (0+test_day|id),
                    data = inf_data, 
            family = bernoulli(),
          #control = list(adapt_delta = 0.99),
          sample_prior = F,
          chains = 4,
          cores = 4,
          #save_all_pars = TRUE,
          iter = 2000)

rinf <- ranef(binf)

rel_inf <- as_tibble(rinf$id[,,"test_dayday1"], rownames = "id")%>%
  left_join(as_tibble(rinf$id[,,"test_dayday2"], rownames = "id")%>%
              rename(Estimate_d2 = Estimate,
                     Q2.5_d2 = Q2.5, 
                     Q97.5_2 = Q97.5, 
                     Est.Error_2 = Est.Error))


ggplot(rel_inf, aes(x = Estimate, y = Estimate_d2))+
  geom_abline(intercept = 0, slope = 1, lty = 2, alpha = 0.7, size = 0.5)+
    geom_point(size = 5, pch = 4)+
  geom_errorbar(aes(ymin = Q2.5_d2, ymax = Q97.5_2),width = 0, alpha = .4)+
  geom_errorbarh(aes(xmin = Q2.5, xmax = Q97.5), height = 0, alpha = .4)+
  labs(x = "Day 1", y = "Day 2")+
  #facet_grid(~chain)+
  stat_cor(method = "pearson", aes(x = Estimate, y = Estimate_d2), inherit.aes = F, size = 3)+
  theme_minimal()
```

```{r}
inf_age <- as_tibble(rinf$id[,,"test_dayday1"], rownames = "id")%>%
  left_join(inf_data)

cor(inf_age$age, inf_age$Estimate)
```

## Task: Card Sorting
```{r}
card_data <- data %>%
  filter(study == "s2", 
         task == "card_sorting")
```

```{r}
bcard <-  brm(correct ~  z_age + (0+test_day|id),
                    data = card_data, 
            family = bernoulli(),
          #control = list(adapt_delta = 0.99),
          sample_prior = F,
          chains = 4,
          cores = 4,
          #save_all_pars = TRUE,
          iter = 2000)

rcard <- ranef(bcard)

rel_card <- as_tibble(rcard$id[,,"test_dayday1"], rownames = "id")%>%
  left_join(as_tibble(rcard$id[,,"test_dayday2"], rownames = "id")%>%
              rename(Estimate_d2 = Estimate,
                     Q2.5_d2 = Q2.5, 
                     Q97.5_2 = Q97.5, 
                     Est.Error_2 = Est.Error))


ggplot(rel_card, aes(x = Estimate, y = Estimate_d2))+
  geom_abline(intercept = 0, slope = 1, lty = 2, alpha = 0.7, size = 0.5)+
    geom_point(size = 5, pch = 4)+
  geom_errorbar(aes(ymin = Q2.5_d2, ymax = Q97.5_2),width = 0, alpha = .4)+
  geom_errorbarh(aes(xmin = Q2.5, xmax = Q97.5), height = 0, alpha = .4)+
  labs(x = "Day 1", y = "Day 2")+
  #facet_grid(~chain)+
  stat_cor(method = "pearson", aes(x = Estimate, y = Estimate_d2), inherit.aes = F, size = 3)+
  theme_minimal()
```

```{r}
card_age <- as_tibble(rcard$id[,,"test_dayday1"], rownames = "id")%>%
  left_join(card_data)

cor(card_age$age, card_age$Estimate)

card_data%>%
  group_by(id)%>%
  summarise(age = mean(age),
            perf = mean(correct))%>%
  ungroup()%>%
  summarise(cor = cor(age ,perf))
```

```{r}
s1_data <- data %>%
  filter(study == "s1")
```

```{r}
bs1 <-  brm(correct ~  z_age + (0+test_day|id/task),
                    data = s1_data, 
            family = bernoulli(),
          #control = list(adapt_delta = 0.99),
          sample_prior = F,
          chains = 4,
          cores = 4,
          #save_all_pars = TRUE,
          iter = 2000)
```




